name = "Switchy Pack"
author = "Sisby folk"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "827cd0c50cdebd46d5e105b72b08126de96c7545566724c42433e6f8ba95be33"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
