name = "Switchy Pack 1.19.4"
author = "Sisby folk"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f736fc934611b7de058fa2b83fc209a65e722b1ff7d21185246436d936277c1"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
