name = "Switchy Pack 1.19.4"
author = "Sisby folk"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7f2468dfba91160e90e7ad508d9059d6e561112aa4a1ed5d42620d50656664c"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"
