name = "Switchy Pack"
author = "Sisby folk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11a23d2c4f1b4e6f4c89ce050c40a3c1fea458ce2ecc352ef6acee9253f0ceb9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
