name = "Switchy Pack (1.20 Forge)"
author = "Sisby folk"
version = "1.2.0+1.20.1+forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "995565f15a43807b516059b5c92156cb997ff0f47d0622f1104cbd0a6eea8822"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
