name = "Switchy Pack 1.19.3"
author = "Sisby folk"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35d3964d5e37f39114035ad49c87799a5db894d5aaf2676c1b39a12844e5524b"

[versions]
minecraft = "1.19.3"
quilt = "0.19.1"
