name = "Switchy Pack (1.19.3)"
author = "Sisby folk"
version = "1.2.0+1.19.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fab7c63f78325ce87b812762adb00c6188132cfed8794d7de7d95d3f1301c626"

[versions]
minecraft = "1.19.3"
quilt = "0.20.2"
